name: Docker Service Continuous Deployment (Compose + SSH)
description: >
  Build, sign, and deploy Docker images with digest-based updates,
  and remotely deploy services via docker-compose over SSH.

inputs:
  dry-run:
    required: false
    default: "false"
    description: Run pipeline without pushing or deploying artifacts

  registry:
    required: true
    description: Image name (e.g. ghcr.io/user/repo)
  service-name:
    required: true
    description: Docker Compose service name

  ssh-host:
    required: true
  ssh-user:
    required: true
  ssh-key:
    required: true
  ssh-port:
    required: false
    default: "22"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - if: inputs.dry-run != 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}

    - id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ inputs.dry-run != 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - if: inputs.dry-run != 'true'
      uses: sigstore/cosign-installer@v3
      with:
        cosign-release: v2.2.4

    - name: Sign the published Docker image (skip on dry-run)
      if: inputs.dry-run != 'true'
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        DIGEST: ${{ steps.build.outputs.digest }}
      shell: bash
      run: |
        echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

    - name: Deploy over SSH (skip on dry-run)
      if: inputs.dry-run != 'true'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.ssh-host }}
        username: ${{ inputs.ssh-user }}
        key: ${{ inputs.ssh-key }}
        port: ${{ inputs.ssh-port }}
        script: |
          SERVICE_NAME=$(echo "${{ inputs.service-name }}" | tr '[:lower:] -' '[:upper:]__' | sed 's/_\+/_/g')
          sed -i "s|^${SERVICE_NAME}_IMAGE_DIGEST=.*|${SERVICE_NAME}_IMAGE_DIGEST=${{ steps.build.outputs.digest }}|" .env
          docker compose up -d --no-deps ${{ inputs.service-name }}
